model:
  type: baseline
  name: google/flan-t5-large

experiment:
  dimension: num_dialogues
  value: 1

debate:
  rounds: 1
  initiator: 1

data:
  sample_size: 150

output:
  dir: results/baseline
  name: dialogs_1