model:
  type: baseline
  name: google/flan-t5-large

experiment:
  dimension: num_dialogues
  value: 2

debate:
  rounds: 2
  initiator: 1

data:
  sample_size: 150

output:
  dir: results/baseline
  name: dialogs_2