model:
  type: fine_tuned
  name: google/flan-t5-large
  lora_path: models/flan-t5-small-cmv-debate-lora

experiment:
  dimension: initiator
  value: agent_1

debate:
  rounds: 6
  initiator: 1

data:
  sample_size: 150

output:
  dir: results/fine_tuned
  name: initiator_1